apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kosmos-prow
  name: tide
  labels:
    app: tide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tide
  template:
    metadata:
      labels:
        app: tide
    spec:
      nodeSelector:
        node: node1
      serviceAccountName: tide
      containers:
        - args:
            - --dry-run=false
            - --github-token-path=/etc/github/oauth
            - --github-endpoint=https://api.github.com
            - --config-path=/etc/config/config.yaml
          image: $(IMAGE_REPOSITORY)/k8s-prow/tide:$(IMAGE_VERSION)
          imagePullPolicy: IfNotPresent
          env:
            - name: IMAGE_REPOSITORY
              value: "cnp-2db5848a.ecis.huabei-3.cmecloud.cn/cnp"
            - name: IMAGE_VERSION
              value: "v20201026-f7d653694b"
          name: tide
          ports:
            - name: http
              containerPort: 8888
          volumeMounts:
            - mountPath: /etc/github
              name: oauth
              readOnly: true
            - mountPath: /etc/config
              name: config
              readOnly: true
      volumes:
        - name: oauth
          secret:
            secretName: oauth-token
        - configMap:
            name: config
          name: config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kosmos-prow
  name: tide
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kosmos-prow
  name: tide
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - create
      - list
      - get
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kosmos-prow
  name: tide
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tide
subjects:
  - kind: ServiceAccount
    name: tide
    namespace: kosmos-prow
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tide
  namespace: kosmos-prow
  name: tide
spec:
  selector:
    app: tide
  ports:
    - name: http
      port: 80
  type: NodePort
