apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
  namespace: kosmos-prow
data:
  plugins.yaml: |
    triggers:
    - repos:
      - kosmos-io
      join_org_url: "https://github.com/kosmos-io/community-infra/blob/main/OWNERS"
      only_org_members: true

    approve:
    - repos:
      - kosmos-io/kosmos
      - kosmos-io/community-infra
      require_self_approval: true
      lgtm_acts_as_approve: false

    lgtm:
    - repos:
      - kosmos-io/kosmos
      - kosmos-io/community-infra
      review_acts_as_lgtm: true

    label:
      additional_labels:
        - tide/merge-method-merge
        - tide/merge-method-rebase
        - tide/merge-method-squash

    size:
      s:   10
      m:   30
      l:   100
      xl:  500
      xxl: 1000

    plugins:
      kosmos-io:
      - approve
      - assign
      - blunderbuss
      - cat
      - cla
      - dog
      - golint
      - heart
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - milestone
      - owners-label

